package view;
import java.io.*;
import jakarta.servlet.*;
import jakarta.servlet.http.*;
public class ManageCategoriesServlet extends HttpServlet{
	public void service(HttpServletRequest req,HttpServletResponse res){
		try{
			res.setContentType("text/html");
			PrintWriter out=res.getWriter();
			out.println("<html>");
			out.println("	<head>");
			out.println("		<meta charset='utf-8'>");
			out.println("		<meta name='viewport' content='width=device-width,initial-scale=1.0'>");
			out.println("		<title>MANAGE CATEGORIES</title>");
			out.println("		<link rel='stylesheet' href='./static/css/style.css'>");
			out.println("	</head>");
			out.println("	<body>");
			out.println("		<nav>");
			out.println("			<div class='container nav_container'>");
			out.println("				<a class='nav_logo' href='/blogsite/home'>BLOG SITE</a>");
			out.println("				<ul class='nav_items'>");
			out.println("					<li><a href='/blogsite/about'>About</a></li>");
			out.println("					<li><a href='/blogsite/contact'>Contact</a></li>");
			out.println("					<li class='categ_menu'><a>Category</a>");
			out.println("						<ul>");
			out.println("							<li><a href='/blogsite/yoga'>Yoga</a></li>");
			out.println("							<li><a href='/blogsite/food'>Food</a></li>");
			out.println("						</ul>");
			out.println("					</li>");
			out.println("					<li><a href='/blogsite/signin'>Signin</a></li>");
			out.println("					<li><a href='/blogsite/signup'>Signup</a></li>");
			out.println("					<li class='nav_profile'>");
			out.println("						<div class='avatar'>");
			out.println("							<img src='./static/images/avatar1.jpg'>");
			out.println("						</div>");
			out.println("						<ul>");
			out.println("							<li><a href='/blogsite/dashboard'>Dashboard</a></li>");
			out.println("							<li><a href='/blogsite/logout'>Logout</a></li>");
			out.println("						</ul>");
			out.println("					</li>");
			out.println("				</ul>");
			out.println("			</div>");
			out.println("		</nav>");
			out.println("		<!--===========================NAV END====================================-->");
			out.println("		<section class='dashboard'>");
			out.println("			<div class='container dashboard_container'>");
			out.println("				<aside>");
			out.println("					<ul>");
			out.println("						<li><a href='/blogsite/addcategory'><h5>Add Category</h5></a></li>");
			out.println("						<li><a href='/blogsite/editcategory'><h5>Edit Category</h5></a></li>");
			out.println("						<li><a href='/blogsite/managecategories.html' class='active'><h5>Manage Categories</h5></a></li>");
			out.println("						<li><a href='/blogsite/addpost'><h5>Add Post</h5></a></li>");
			out.println("						<li><a href='/blogsite/editpost'><h5>Edit Post</h5></a></li>");
			out.println("						<li><a href='/blogsite/manageposts'><h5>Manage Posts</h5></a></li>");
			out.println("				</aside>");
			out.println("				<main>");
			out.println("					<table>");
			out.println("						<thead>");
			out.println("							<th>Category</th>");
			out.println("							<th>Description</th>");
			out.println("							<th>Edit</th>");
			out.println("							<th>Delete</th>");
			out.println("						</thead>");
			out.println("						<tbody>");
			out.println("							<tr>");
			out.println("								<td>Art</td>");
			out.println("								<td>jhhfjv jhvk</td>");
			out.println("								<td><a href='/blogsite/editcategory.html' class='btn sm'>Edit</a></td>");
			out.println("								<td><a href='/blogsite/deletecategory.html' class='btn danger'>Delete</a></td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Art</td>");
			out.println("								<td>gjhk klkn</td>");
			out.println("								<td><a href='/blogsite/editcategory.html' class='btn sm'>Edit</a></td>");
			out.println("								<td><a href='/blogsite/deletecategory.html' class='btn danger'>Delete</a></td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Art</td>");
			out.println("								<td>fgjhj ghhkjlk</td>");
			out.println("								<td><a href='/blogsite/editcategory.html' class='btn sm'>Edit</a></td>");
			out.println("								<td><a href='/blogsite/deletecategory.html' class='btn danger'>Delete</a></td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Art</td>");
			out.println("								<td>gfjhj kbjn</td>");
			out.println("								<td><a href='/blogsite/editcategory.html' class='btn sm'>Edit</a></td>");
			out.println("								<td><a href='/blogsite/deletecategory.html' class='btn danger'>Delete</a></td>");
			out.println("							</tr>");
			out.println("						</tbody>");
			out.println("					</table>");
			out.println("				</main>");
			out.println("			</div>");
			out.println("		</section>");
			out.println("		<!--===============================MANAGE END====================================================-->");
			out.println("		<footer>");
			out.println("            <div class='container footer_container'>");
			out.println("                <article>");
			out.println("                    <h1>Categories</h1>");
			out.println("                    <ul>");
			out.println("                        <li><a href='/blogsite/#'>Art</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Wild Craft</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Yoga</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Sports</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Food</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Entertainment</a></li>");
			out.println("                </article>");
			out.println("                <article>");
			out.println("                    <h1>Blog</h1>");
			out.println("                    <ul>");
			out.println("                        <li><a href='/blogsite/#'>Safety</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Repair</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Recent</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Popular</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Categories</a></li>");
			out.println("                </article>");
			out.println("                <article>");
			out.println("                    <h1>Permalinks</h1>");
			out.println("                    <ul>");
			out.println("                        <li><a href='/blogsite/#'>Home</a></li>");
			out.println("                        <li><a href='/blogsite/#'>About</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Services</a></li>");
			out.println("                        <li><a href='/blogsite/#'>Contact</a></li>");
			out.println("                </article>");
			out.println("            </div>");
			out.println("            <div class='footer_copyright'>");
			out.println("                <small>Copyright &copy; Blog Site All Rights Reserved</small>");
			out.println("            </div>");
			out.println("        </footer>");
			out.println("        <!--===============================================FOOTER END=======================================-->");
			out.println("    </body>");
			out.println("</html>");
		}
		catch(Exception e){
			System.out.println(e);
		}
	}
}